Weighted consensus fix & refactoring
Malkovsky/distributed-learning pull request #2
Opened 2020-10-26 13:02 UTC by vsalavatov

2020-10-28 10:02 UTC, Malkovsky requested changes

2020-10-28 10:02 UTC, Malkovsky commented on notebooks/consensus.py
> +'''
Наверно стоит убрать например в `src/`, в ноутбуке дописать что-нибудь в духе 
```
import os
import sys
module_path = os.path.abspath(os.path.join('..', 'src'))
if module_path not in sys.path:
    sys.path.append(module_path)
```

2020-10-30 17:24 UTC, Malkovsky requested changes
надо бы убрать consensus.py в utils/ и соответственно в ноутбуке тоже путь поменять, можно заодно переименовать в consensus_acyncio.py

2020-11-01 14:05 UTC, vsalavatov commented on notebooks/consensus.py
> +'''
done

2020-11-01 16:23 UTC, Malkovsky approved these changes
ok

2020-11-01 16:23 UTC, merged